services:
  contacts.db:
    container_name: contacts-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd1
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: contacts-messagebroker
    hostname: contacts-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  contact.api:
    container_name: contacts-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MessageBroker__Host=amqp://contacts-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on: [messagebroker]
    ports:
      - "6101:8080"
      - "6161:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  contact-persistency.api:
    container_name: contacts-persistence-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=contacts.db;Database=ContactManagerDb;User Id=sa;Password=P@ssw0rd1;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://contacts-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on: [contacts.db, messagebroker]
    ports:
      - "6102:8080"
      - "6162:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
